name: Huntsville Life
favicon: null
layout_spectrum: 0.4070479664951563
typography_spectrum: 0.16676255711354315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10056424280628562
  lightness: 0.49569128663279116
  saturation: 0.6208942497614771
  rhythmicContrast: 0.48076015594415367
purpose: []
